### ISSUE TITLE
Client support for multithreaded tokio environment

### ISSUE THREAD

**Issue by jsnnerve** [slowtec/tokio-modbus#108]
Hi,

Currently there is only support for a single threaded tokio environment for clients, but would it be possible to add support for a multithreaded tokio environment?

**Comment by uklotzde** [comment]
Not planned.

The implicit runtime for the sync features remains single-threaded. Implement your own blocking behavior on behalf of the async API when needed. The async API does does not depend o any particular runtime instance.

See also: #145
