### ISSUE TITLE
Performance benchmarks compared to libmodbus

### ISSUE THREAD

**Issue by ShayBox** [slowtec/tokio-modbus#126]
I ran some benchmarks between `tokio-modbus` and `libmodbus`, here are my results.  
I only tested reading multiple registers as this is my main use-case, maybe other actions would perform differently, test for your use-case.

```rust
use criterion::{criterion_group, criterion_main, Criterion};
use libmodbus::{ModbusClient, ModbusRTU};
use tokio_modbus::prelude::SyncReader;

fn criterion_benchmark(c: &mut Criterion) {
    let builder = tokio_serial::new("/dev/ttyUSB0", 115200);
    let slave = tokio_modbus::slave::Slave(1);
    let mut ctx = tokio_modbus::prelude::sync::rtu::connect_slave(&builder, slave).unwrap();
    c.bench_function("tokio_modbus", move |b| {
        b.iter(|| ctx.read_holding_registers(0, 100).unwrap());
    });

    let mut modbus = libmodbus::Modbus::new_rtu("/dev/ttyUSB0", 115200, 'N', 8, 1).unwrap();
    modbus.set_slave(1).unwrap();
    modbus.connect().unwrap();
    c.bench_function("libmodbus", move |b| {
        let mut dest = vec![0u16; 100];
        b.iter(|| modbus.read_registers(0, 100, &mut dest).unwrap());
    });
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```

115200 Baudrate:
```
tokio_modbus            time:   [26.720 ms 26.849 ms 26.984 ms]
libmodbus               time:   [26.624 ms 26.748 ms 26.875 ms]
```

230400 Baudrate:
```
tokio_modbus            time:   [17.286 ms 17.426 ms 17.565 ms]
libmodbus               time:   [17.339 ms 17.458 ms 17.576 ms]
```

I was unable to test higher as my serial device times out, but it's safe to say in this case there's no difference, and the ease of use with `tokio_modbus` outweighs the need for clang in the build system to use `libmodbus` for me.

**Comment by CosminPerRam** [comment]
Thanks for doing this benchmark, happy to hear that `tokio_modbus` has absolute minimal (or non existent? every result is +/- 0.5% max (which I think is normal)) overhead against `libmodbus`.

**Comment by ShayBox** [comment]
It does appear to have no difference, however I found I was able to achieve a step higher baud rate with Tokio mod us over libmodbus so it is faster for me. But I'm going over my serial devices max baud rate and encountering expected issues.

**Comment by uklotzde** [comment]
Closing as completed as there is nothing left to do here.

If you think that benchmarks should be added to the project then please submit a PR.
