### ISSUE TITLE
Could not find 'tcp' in 'server'

### ISSUE THREAD

**Issue by RayofLightz** [slowtec/tokio-modbus#147]
Currently when trying to compile the tcp-server example with the following Carog.toml I get the above error.
```
[dependencies]
tokio-modbus = { version = "*", default-features = false, features = ["tcp", "server"] }
```

I am on the current stable release of rust.

**Comment by uklotzde** [comment]
You need to use "tcp-server-unstable", see the Cargo.toml.

The server features are considered experimental and are hardly documented, see also #146.

**Comment by uklotzde** [comment]
https://github.com/slowtec/tokio-modbus/pull/148
