### ISSUE TITLE
rtu over tcp

### ISSUE THREAD

**Issue by pnpdb** [slowtec/tokio-modbus#177]
Is there any implementation of modbus rtu over tcp?

**Comment by pnpdb** [comment]
![3681679630039_ pic](https://user-images.githubusercontent.com/8870891/227420383-7d3149e6-0d88-4bc0-8f3d-af4f79e78786.jpg)

Here is a simple explanation about RTU over TCP

**Comment by pnpdb** [comment]
http://www.simplymodbus.ca/TCP.htm
Here is a simple explanation about RTU over TCP.
![3681679630039_ pic](https://user-images.githubusercontent.com/8870891/227420675-16a17766-65e2-442b-bae3-af3b5711ed2f.jpg)

**Comment by imawaki** [comment]
@pnpdb does this question relate? https://github.com/hirschenberger/modbus-rs/issues/37
@uklotzde is it difficult to implement?

**Comment by uklotzde** [comment]
Before thinking about possible implementations I recommend to start evaluating the implications for the API and how it needs to be changed or extended. Then open a Draft PR for discussion.

**Comment by cdbennett** [comment]
Could be interesting to be able to do this. But, seems like quite an edge case, how many people actually would use this? Is this the best way to really solve the problem you have? Maybe you could explain the bigger picture.

The way I've usually seen access to Modbus RTU devices done recently is to use a Modbus TCP to Modbus RTU gateway device. Typically this is a little embedded hardware device costing $100-$1000. But it could be a pure software component too that has a Modbus TCP server and Modbus RTU client in one application -- this would be more general purpose and clean, I think. We could implement such a software gateway using tokio-modbus.

**Comment by wheregmis** [comment]
I am currently trying to combine server and client into one application, the purpose is different in my case but is doable. I am currently bridging multiple tcp sources under one server. If my workspace will have anything similar kind of use case, i will try to put some more insights.

**Comment by barisdigi** [comment]
This is the issue preventing us from using tokio-modbus, some gateway devices unfortunately only support modbus rtu over tcp

**Comment by uklotzde** [comment]
> This is the issue preventing us from using tokio-modbus, some gateway devices unfortunately only support modbus rtu over tcp

Then why don't you implement the missing pieces and and submit a PR?

**Comment by HrvojeJuric** [comment]
u can connect rtu over tcp like this

```rust
let transport = TcpStream::connect(id.socket).await?;
tokio_modbus::prelude::rtu::attach_slave(transport, slave)
```

this works for me

**Comment by uklotzde** [comment]
Does the server-side implementation added in #228 fix this issue or is the client-side part missing?

**Comment by uklotzde** [comment]
I will close this issue. Please create a new, more specific issue for any missing parts.
