### ISSUE TITLE
Move from tokio-core and tokio-proto to tokio

### ISSUE THREAD

**Issue by cbourjau** [slowtec/tokio-modbus#18]
First and foremost! Thanks a lot for sharing this library! I was trying to use it today and noticed that it uses the deprecated `tokio-core` and `tokio-proto` crates. Is there any particular issue holding back the migration to the current `tokio` crate?

**Comment by flosse** [comment]
@cbourjau Your suggested migration is totally in our minds :)
Unfortunately there is no drop-in replacement of `tokio-proto` so we have to refactor the current implementation first. There is an ongoing progress in #10 :)

BTW:
Contributions are very welcome ;-)

**Comment by flosse** [comment]
According to https://github.com/tokio-rs/tokio/issues/118#issuecomment-452969665 https://github.com/tower-rs/tokio-tower seems to be the replacement for `tokio-proto` but it seems to be buggy: https://github.com/tower-rs/tokio-tower/issues/2

**Comment by uklotzde** [comment]
tokio-proto complicates handling of timeouts as discussed in #12

**Comment by flosse** [comment]
now there is no more tokio-proto in the master :)
