### ISSUE TITLE
No timeout in the RTU client async implementation

### ISSUE THREAD

**Issue by gustavowd** [slowtec/tokio-modbus#183]
Hi, is there any way to enable timeout in the rtu async client in the tokio-modbus?
In the sync RTU client it is possible by using "sync::rtu::connect_slave_with_timeout", but i can't find any way to do that in the async mode. Any thougths about it?

**Comment by uklotzde** [comment]
https://docs.rs/futures/latest/futures/future/fn.select.html

**Comment by uklotzde** [comment]
Ready to use: https://docs.rs/futures-time/latest/futures_time/
