### ISSUE TITLE
write_multiple_registers taking array as a param

### ISSUE THREAD

**Issue by jackstar12** [slowtec/tokio-modbus#205]
I am currently using this library (really like it) and was wondering why the `write_multiple_registers` function takes the input in form of an array? This is a bit of a pain and the data is turned `to_vec()` directly anyways. 

https://github.com/slowtec/tokio-modbus/blob/5fc09c4ef31eaf8d9fb55eccb84230e6cc429fd7/src/client/mod.rs#L289-L308

Is there any intention behind this?

**Comment by uklotzde** [comment]
I don't remember the details. If you have an idea how to improve the API please submit a PR for discussion.

**Comment by jackstar12** [comment]
> I don't remember the details. If you have an idea how to improve the API please submit a PR for discussion.

I thought of changing it to `Vec<Word>` because thats whats used internally aswell. Ill create a pr

**Comment by uklotzde** [comment]
Using `Cow` might be beneficial here. This will cause a breaking API change and inconveniences for users. The latter could be mitigated by introducing helper methods. I am exploring such an extension.
