### ISSUE TITLE
Dev Dependencies: Upgrade rustls-pemfile and tokio-rustls

### ISSUE THREAD

**Issue by uklotzde** [slowtec/tokio-modbus#233]

**Comment by gustavowd** [comment]
In order to compile the aws-lc-sys v0.13.3 library, that is request for the new version of rustls, I have to install some packets in ubuntu. I don´t now how to do this in the pull request autotest. This are the packets:

sudo apt install bindgen cmake libclang-dev

Thanks in advance

**Comment by uklotzde** [comment]
> I don´t now how to do this in the pull request autotest.

Me neither. Someone needs to study the install instruction for each platform and apply them somehow :shrug:

Getting rid of unneeded dependencies would be even better. Each of them is a burden.

**Comment by uklotzde** [comment]
Follow-up: #256
