### ISSUE TITLE
SECS/GEM SEMI?

### ISSUE THREAD

**Issue by han1548772930** [slowtec/tokio-modbus#263]
Hello, I would like to ask if this can be used for SECS/GEM SEMI?

**Comment by jerrywrice** [comment]
If you're asking if Modbus is usable for accessing/controlling sensors and/or actuators from a running SECS/GEM interface library, then there is no inherent issue - assuming you use the Rust FFI or have a native Rust SECS/GEM library. If you're instead asking if a Modbus protocol port can be directly connected as a matching remote end-port to a SECS/GEM link, then the answer is no. Modbus and SECS/GEM are totally  incompatible network protocols.

**Comment by han1548772930** [comment]
> If you're asking if Modbus is usable for accessing/controlling sensors and/or actuators from a running SECS/GEM interface library, then there is no inherent issue - assuming you use the Rust FFI or have a native Rust SECS/GEM library. If you're instead asking if a Modbus protocol port can be directly connected as a matching remote end-port to a SECS/GEM link, then the answer is no. Modbus and SECS/GEM are totally incompatible network protocols.

Thanks for your reply
