### ISSUE TITLE
Cant ignore Modbus RTU Request

### ISSUE THREAD

**Issue by philippderdiedas** [slowtec/tokio-modbus#264]
Commit b4819768309dffce04145984dafdeb2a6a5355d6 prevents modbus (rtu) server from ignoring response.
trait requires Response to be `crate::Response` instead of own type e.g. `Option<crate::Response>`
So #141 `Ok(None)` does not work anymore

**Comment by uklotzde** [comment]
Looks like this feature got lost during the refactoring. It was informally proposed as a solution, but no one has provided a test for this use case.

**Comment by uklotzde** [comment]
Please test #265.

You may also add regression tests for your use case if you want to make sure that it remains covered.

**Comment by philippderdiedas** [comment]
works like a charm 👍
