### ISSUE TITLE
tokio-modbus version 0.16.1 failing to connect in several devices

### ISSUE THREAD

**Issue by gustavowd** [slowtec/tokio-modbus#312]
I'm using tokio-modbus in several gateway for about 1 year and it working perfectly. However, when i updated the library to version 0.16.1, I was unable to connect with several devices in my system (modbus TCP). Any reason why this is happening?

**Comment by flosse** [comment]
Can you describe in more detail what kind of error messages you are getting?

**Comment by gustavowd** [comment]
> 🤔 do you have the opportunity to inspect the devices?

These are commercial devices, meters from a Brazilian company. Therefore, I do not have access to how they work. To try to help, I have two types of meters. I can connect to one of them and exchange data. With the other type, the connection fails due to timeout. It always worked with tokio-modbus up to version 0.15.0. My code implement a gateway for 27 devices, but only 4 of them connect when using tokio-modbus 0.16.1.

**Comment by flosse** [comment]
Alright, then we need to take a closer look at what has changed since `v0.15.0`.
Unfortunately I don't have much time at the moment. I'll see what I can maybe do later.

**Comment by gustavowd** [comment]
> Alright, then we need to take a closer look at what has changed since `v0.15.0`. Unfortunately I don't have much time at the moment. I'll see what I can maybe do later.

Thanks. I found that version 0.16.0 works as well. The problem is in version 0.16.1.

**Comment by gustavowd** [comment]
> > Alright, then we need to take a closer look at what has changed since `v0.15.0`. Unfortunately I don't have much time at the moment. I'll see what I can maybe do later.
> 
> Thanks. I found that version 0.16.0 works as well. The problem is in version 0.16.1.

I realized that I had turned on the tcp-server feature, even though I wasn't using it. When I removed it and left only the tcp feature, it worked with version 0.16.1.

**Comment by uklotzde** [comment]
I don't understand how enabling the server feature could cause client-side connection failures? Please re-enable it, rebuild,  and re-test. If it does not occur again it was most likely just a hiccup of your local build and we should close this issue.

**Comment by gustavowd** [comment]
Sorry guys. It was a hardware failure. I rebooted the meters and all started to work again.
It was completely random, sometimes it worked and sometimes it didn't. There was a time when even going back to version 0.14.0 didn't work. So I came to the conclusion that the problem wasn't on tokio-modbus' side.

Thanks and sorry again.
