### ISSUE TITLE
Modbus TCP / RTU Gateway

### ISSUE THREAD

**Issue by hanusek** [slowtec/tokio-modbus#37]
Hello. 
I need simple example with modbus gateway - TCP Server/RTU master(serial port).
Please help me.

**Comment by flosse** [comment]
> Please help me.

Could you provide a bit more information?
Do you have a repository with your current implementation?
Where exactly do you need help?

**Comment by hanusek** [comment]
> > Please help me.
> 
> Could you provide a bit more information?
> Do you have a repository with your current implementation?
> Where exactly do you need help?

Hello, Thx for reply.
My repo: https://github.com/hanusek/ModbusGateway

**Comment by flosse** [comment]
> My repo: https://github.com/hanusek/ModbusGateway

hm.... I just receive an 404 :-\

**Comment by hanusek** [comment]
> > My repo: https://github.com/hanusek/ModbusGateway
> 
> hm.... I just receive an 404 :-\

OK. I'm fixed it. Check now.

**Comment by flosse** [comment]
I cannot see the usage of `tokio-modbus` in your code.
Please checkout the [examples](https://github.com/slowtec/tokio-modbus/blob/master/examples/) first, try to adjust them for your usecase and precisely describe your problem or question.

**Comment by flosse** [comment]
I'm going to close this issue until it's clear what's exactly the question/problem. Feel free to reopen it. If you need commercial support you're welcome to contact us.
