### ISSUE TITLE
RTU example panics with BorrowMutError

### ISSUE THREAD

**Issue by rspendl** [slowtec/tokio-modbus#41]
Running the rtu-example panics with:

> Reading a sensor value from Slave(2)
> thread 'main' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:1188:5

Deleting lines 67 and 68 fixes the issue.

**Comment by flosse** [comment]
Thanks for reporting!

**Comment by flosse** [comment]
fixed: 13e23dcac96d3e2e2d561dc94dcc126bb64f44b5
