### ISSUE TITLE
Derive Debug for Context

### ISSUE THREAD

**Issue by flosse** [slowtec/tokio-modbus#55]
Blocked by 
- ~https://github.com/berkowski/mio-serial/pull/20~
- https://github.com/berkowski/tokio-serial/pull/27

**Comment by MightyPork** [comment]
Not blocked anymore, this would be useful to have

**Comment by flosse** [comment]
> Not blocked anymore, this would be useful to have

now it's blocked by https://github.com/berkowski/tokio-serial/pull/27
