### ISSUE TITLE
How to use it？

### ISSUE THREAD

**Issue by deeptuuk** [slowtec/tokio-modbus#63]
I am sorry，i am a newest ruster。

when i use you code,
i got below error 

cargo run
feature `tcp` is required to run this example

can you help me !
appreciate you!!!!!!!!!!!!!!!!
------------------------
ps: I am really not understand how to use rust features.

**Comment by flosse** [comment]
Please see https://doc.rust-lang.org/cargo/reference/features.html#usage-in-end-products

**Comment by deeptuuk** [comment]
thank you so much
