### ISSUE TITLE
consider using `async_trait`

### ISSUE THREAD

**Issue by bootrecords** [slowtec/tokio-modbus#82]
This is more of an internal structuring thing, but I noticed that in many parts of the code base explicit `Pin<Box<dyn Future<...>>>`s are returned.
While this works, it's a bit tedious to read, so using [async-trait](https://crates.io/crates/async-trait) may be worth considering for the internal traits, such as `Client`, `Reader` and `Writer`.

**Comment by uklotzde** [comment]
I second that.
